<?php

return [
    'whatsapp_url' => 'https://wa.me/542612476927?text=Hola%2C%20vi%20la%20landing%20del%20sistema%20de%20gestion%20comercial%20y%20quiero%20consultar%20por%20la%20implementacion%20y%20los%20planes%20disponibles.',
    'hero_highlights' => [
        [
            'title' => 'Operacion diaria ordenada',
            'description' => 'Ventas, compras y stock sincronizados por comercio desde un solo lugar.',
        ],
        [
            'title' => 'Inventario mas controlado',
            'description' => 'Productos, categorias, proveedores, lotes y vencimientos dentro del mismo flujo.',
        ],
        [
            'title' => 'Seguimiento automatico',
            'description' => 'Dashboard operativo y alertas por mail para actuar antes de que aparezca el problema.',
        ],
    ],
    'core_features' => [
        'Ventas y compras con impacto automatico en stock.',
        'Productos, categorias, proveedores y usuarios internos.',
        'Lotes, vencimientos y alertas por mail configurables.',
        'Operacion por comercio lista para correr en Laravel Cloud.',
    ],
    'plan_summaries' => [
        [
            'title' => 'Implementacion inicial',
            'price' => 'Desde ARS 95.000',
            'description' => 'Tres planes cerrados segun el volumen inicial del catalogo: 30, 100 o 250 productos.',
        ],
        [
            'title' => 'Carga adicional',
            'price' => 'Desde $500 por producto',
            'description' => 'Disponible para ampliaciones posteriores, no como reemplazo del plan inicial.',
        ],
        [
            'title' => 'Mantenimiento mensual',
            'price' => 'Desde ARS 25.000 / mes',
            'description' => 'Soporte, correcciones y mejoras menores para sostener la operacion.',
        ],
    ],
    'pricing_notes' => [
        'Los valores finales dependen del alcance inicial y del volumen de productos.',
        'La carga adicional aplica solo para productos extra fuera del plan inicial contratado.',
        'No incluye desarrollos personalizados ni integraciones a medida.',
    ],
    'business_types' => ['Kioscos', 'Tiendas', 'Ferreterias', 'Petshops', 'Regalerias', 'Autoservicios'],
    'pricing_sections' => [
        [
            'key' => 'implementation',
            'title' => 'Instalacion inicial',
            'description' => 'Opciones de arranque para distintos tamanos de comercio y nivel de acompanamiento.',
            'plans' => [
                [
                    'code' => 'express',
                    'title' => 'Plan Express',
                    'subtitle' => 'Pago unico',
                    'description' => 'Para comercios chicos que quieren salir a operar con una configuracion base.',
                    'amount' => 95000,
                    'price' => '95.000',
                    'priceLabel' => 'ARS',
                    'features' => [
                        'Configuracion base del sistema',
                        'Capacitacion breve de arranque',
                        'Hasta 30 productos incluidos',
                        'Acompanamiento inicial',
                    ],
                ],
                [
                    'code' => 'esencial',
                    'title' => 'Plan Esencial',
                    'subtitle' => 'Pago unico',
                    'description' => 'La opcion recomendada para la mayoria de los comercios que quieren una puesta en marcha ordenada.',
                    'amount' => 150000,
                    'price' => '150.000',
                    'priceLabel' => 'ARS',
                    'featured' => true,
                    'features' => [
                        'Instalacion y configuracion inicial',
                        'Capacitacion completa',
                        'Hasta 100 productos incluidos',
                        'Ajustes de arranque',
                    ],
                ],
                [
                    'code' => 'plus',
                    'title' => 'Plan Plus',
                    'subtitle' => 'Pago unico',
                    'description' => 'Pensado para comercios con catalogo amplio o una operatoria mas exigente desde el inicio.',
                    'amount' => 220000,
                    'price' => '220.000',
                    'priceLabel' => 'ARS',
                    'features' => [
                        'Implementacion completa',
                        'Hasta 250 productos incluidos',
                        'Capacitacion por sectores',
                        'Ajustes operativos iniciales',
                    ],
                ],
            ],
        ],
        [
            'key' => 'product_loading',
            'title' => 'Carga de productos',
            'description' => 'Servicios de ampliacion para productos extra fuera del paquete inicial contratado.',
            'plans' => [
                [
                    'code' => 'unitario',
                    'title' => 'Carga adicional por unidad',
                    'subtitle' => 'Flexible',
                    'description' => 'Ideal para ampliaciones puntuales o correcciones fuera del paquete incluido.',
                    'amount' => 500,
                    'price' => '$500',
                    'priceSuffix' => 'por producto',
                    'features' => [
                        'Para ampliaciones o ajustes del catalogo',
                        'Carga manual individual',
                        'Revision basica de datos',
                    ],
                ],
                [
                    'code' => 'pack100',
                    'title' => 'Pack 100 productos',
                    'subtitle' => 'Pago unico',
                    'description' => 'Pensado para ampliaciones posteriores cuando el catalogo ya supero lo incluido en el plan.',
                    'amount' => 45000,
                    'price' => '45.000',
                    'priceLabel' => 'ARS',
                    'features' => [
                        '100 productos adicionales',
                        'Carga estructurada',
                        'Validacion general del listado',
                    ],
                ],
                [
                    'code' => 'pack250',
                    'title' => 'Pack 250 adicionales',
                    'subtitle' => 'Pago unico',
                    'description' => 'Para ampliaciones grandes sobre un comercio ya implementado, sin reemplazar el plan inicial.',
                    'amount' => 95000,
                    'price' => '95.000',
                    'priceLabel' => 'ARS',
                    'features' => [
                        '250 productos adicionales',
                        'Carga masiva asistida',
                        'Revision de categorias y precios',
                    ],
                ],
            ],
        ],
        [
            'key' => 'maintenance',
            'title' => 'Mantenimiento mensual',
            'description' => 'Niveles de soporte para sostener la operacion, resolver incidentes y sumar mejoras menores.',
            'plans' => [
                [
                    'code' => 'basico',
                    'title' => 'Plan Basico',
                    'subtitle' => 'Mensual',
                    'description' => 'Cobertura simple para mantener el sistema estable y con acompanamiento continuo.',
                    'amount' => 25000,
                    'price' => '25.000',
                    'priceSuffix' => '/ mes',
                    'features' => [
                        'Soporte continuo',
                        'Correccion de errores',
                        'Actualizaciones menores',
                        'Respuesta standard',
                    ],
                ],
                [
                    'code' => 'operativo',
                    'title' => 'Plan Operativo',
                    'subtitle' => 'Mensual',
                    'description' => 'Mas seguimiento para comercios con mayor uso diario y necesidad de respuesta frecuente.',
                    'amount' => 45000,
                    'price' => '45.000',
                    'priceSuffix' => '/ mes',
                    'features' => [
                        'Todo lo del plan basico',
                        'Prioridad media en soporte',
                        'Revision mensual operativa',
                        'Bonificacion parcial en ajustes menores',
                    ],
                ],
                [
                    'code' => 'prioritario',
                    'title' => 'Plan Prioritario',
                    'subtitle' => 'Mensual',
                    'description' => 'Para negocios que necesitan seguimiento mas cercano y mayor velocidad de respuesta.',
                    'amount' => 60000,
                    'price' => '60.000',
                    'priceSuffix' => '/ mes',
                    'features' => [
                        'Prioridad alta en soporte',
                        'Seguimiento mas cercano',
                        'Bolsa mensual para ajustes menores',
                        'Planificacion de mejoras puntuales',
                    ],
                ],
            ],
        ],
    ],
];
